version: 2
updates:
  # Enable version updates for Python's pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
